name: Acceptance Tests

on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Acceptance Tests
        uses: terraformtesting/acceptance-tests@v1
        with:
          PROVIDER_PATH: '.'
          PROVIDER_NAME: terraform-provider-github
          SWEEPER_REGIONS: gh-region
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER: github-terraform-test-user
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GITHUB_TEST_USER_TOKEN }}
          GITHUB_TEST_COLLABORATOR: github-terraform-test-collaborator
          GITHUB_TEST_COLLABORATOR_TOKEN: ${{ secrets.GITHUB_TEST_COLLABORATOR_TOKEN }}
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
