name: Acceptance Tests

on:
  push:
    branches:
      - master

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Generate Test Fixtures
        run: |
          openssl req -x509 -newkey rsa:4096 -days 1 -nodes \
          -subj "/C=US/ST=test/L=test/O=test/CN=localhost" \
          -keyout github/test-fixtures/key.pem -out github/test-fixtures/cert.pem
      - name: Acceptance Tests
        uses: terraformtesting/acceptance-tests@v1
        with:
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER: github-terraform-test-user
          GITHUB_TEST_USER_TOKEN: ${{ secrets.GITHUB_TEST_USER_TOKEN }}
          GITHUB_TEST_COLLABORATOR: github-terraform-test-collaborator
          GITHUB_TEST_COLLABORATOR_TOKEN: ${{ secrets.GITHUB_TEST_COLLABORATOR_TOKEN }}
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
